### ISSUE TITLE
Fjerne moment

### ISSUE THREAD

**Issue by nutgaard** [navikt/datovelger#42]
`moment` pakken er en [relativt stor pakke](https://bundlephobia.com/result?p=moment@2.27.0) å laste ned, og selv etter tree-shaking så er størrelsen i overkant av hva vi ønsker å ha med for enkle dato-beregninger (rundt 60KB ifølge `source-map-explorer`).

To alternativer som kan vurderes; 
1. bytte til date-fns som er ett [vesentlig mindre bibliotek](https://bundlephobia.com/result?p=date-fns@2.15.0), og er kun basert på enkle funksjoner som gjør tree-shaking mer effektivt.
2. bruke standard javascript funksjonalitet

**Comment by erlendev** [comment]
Opprettet PR https://github.com/navikt/datovelger/pull/55, riktig nok med omskrivning til [dayjs](https://github.com/iamkun/dayjs) og ikke date-fns

**Comment by erlendev** [comment]
Lukkes etter merge av #55
