### ISSUE TITLE
UU: kontraster

### ISSUE THREAD

**Issue by ninakjek** [navikt/datovelger#54]
Per nå tilfredsstiller ikke fargen på ukedag-labels og de røde dagene UU-krav til kontrast. Designer foreslår følgende endring:

Ukedag-labels (.DayPicker-Weekday): @navGra80 (#59514B) 
Røde dager (.nav-datovelger .DayPicker-Day:last-child): @ redError(#BA3A26) 

Se forskjellen på bildene: 
![Skjermbilde 2020-11-02 kl  14 07 56](https://user-images.githubusercontent.com/5719550/97872186-e77a4200-1d15-11eb-99fd-9bcee3ed4113.png)
![Skjermbilde 2020-11-02 kl  14 12 34](https://user-images.githubusercontent.com/5719550/97872188-e812d880-1d15-11eb-9f3e-fd3fab48ba9d.png)

Vi ser at de røde dagene kan gå litt inn i de sorte her, men det var den lyseste rødfargen i nav designsystem som tilfredsstilte UU-krav. 

Er dette noe som kan være aktuelt å endre i komponenten? :)

**Comment by frodehansen2** [comment]
Kontraster er nå forbedret og tilgjengelig i versjon 8.0.3

![image](https://user-images.githubusercontent.com/462494/100802693-2b9e5680-342a-11eb-9be6-c4f53c6e872f.png)
