### ISSUE TITLE
Bumping feiler for familie-ba-sak-frontend

### ISSUE THREAD

**Issue by henninghaakonsen** [navikt/datovelger#56]
Prøver å bumpe til nyeste versjon og får følgende feilmelding:

yarn add nav-datovelger
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/dayjs-timezone/-/dayjs-timezone-0.5.31.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/henninghaakonsen/nav/familie/familie-ba-sak-frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by erlendev** [comment]
Får ikke reprodusert denne med `yarn add nav-datovelger` eller `yarn add nav-datovelger dayjs` i et tomt yarn-prosjekt... Usikker på hvordan dette har skjedd, men ser ut som det er en pakke dere prøver å hente som ikke finnes på yarnpkg.com. 

Prøvd å resette `yarn.lock` @henninghaakonsen?

**Comment by henninghaakonsen** [comment]
haha, det fungerte 👍
